project:
  type: website

#Configuration de la langue 
lang: fr

execute:
  freeze: auto

website:
  title: "*Portfolio* 📊🗂️📈"
  back-to-top-navigation: true
  page-footer:
    background: primary
    foreground: white
    
    left: 
      - icon: wrench-adjustable
        text: Website made with **Quarto**
        href: https://quarto.org/
    
    center:
      - text: "© 2024, François BOUSSENGUI"
    
    right: 
      - icon: cc-circle
        text: "Licence : CC BY-NC-SA"

  
  navbar:
    background: primary
    right:
      - text: "Accueil"
        href: index.qmd
        
      - text: "Compétences"
        href: posts/skills.qmd

      - text: "Travaux"
        href: posts/index.qmd
    

format:
  html:
    theme: theme.scss
    extensions: [fontawesome]
    googlefonts: 
      - family: "Roboto"
        weights: [400, 700]
      - family: "Merriweather"
        weights: [400, 700]
    toc: true
    pagetitle: "François BOUSSENGUI | {{< meta title >}}"
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    

editor: visual


comments:
  utterances:
    repo: francois-b-24/utterance


