---
title: "Mon parcours"
smooth-scroll: true
comments: false
author: ""
---

::: {.timeline}

::: {.timeline-event}
::: {.timeline-point .bg_2}
:::
::: {.timeline-content}
::: {.timeline-border .bg_2}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Statisticien  
{{< fa building >}} **Aon France**  
{{< fa calendar-days >}} 02/2023 - Présent  
{{< fa location-dot >}} *35 rue de la fédérarion, 75015, Paris, France*  

- **Industrialisation Python & automatisation** : création d'applications python **Streamlit** destinées aux équipes métiers → Gain de temps conséquent dans la réalisation de tâches répétitives. 
- **Migration SAP BO → MyReport** : pilotage de la migration (recueil des besoins, cartographie des rapports, formation des utilisateurs). 
- **Outils d’aide au pilotage** : développement d'applications python **Streamlit** internes dédiées aux brokers pour le pilotage de leur activité.
- **Tableaux de bord suivi de la sinistralité** : création de tableaux de bord interactifs **Qlik Sense** à destination des clients, avec KPI : taux de fréquence, coût moyen, répartition de la charge sinistralité.
:::  
:::  
:::

::: {.timeline-event}
::: {.timeline-point .bg_3}
:::
::: {.timeline-content}
::: {.timeline-border .bg_3}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Data Analyst  
{{< fa building >}} **Ascentiel Group**  
{{< fa calendar-days >}} 11/2021 – 02/2023  
{{< fa location-dot >}} *18 Rue des 2 Gares, 92500 Rueil-Malmaison, France*  

- **Robot de scraping tarifaire** : développement d’un pipeline Python/Selenium pour collecter quotidiennement les tarifs concurrents (assurance chiens/chats), fiabilisation du taux de récupération à **95%**.
- **Analyse des résultats techniques des produits** : élaboration de rapports sur les performances des couvertures présentés mensuellement au responsable et aux équipes.   
- **Simulations tarifaires & recettage** : mise en place d’un environnement de test **MySQL**, simulation de scénarios de tarification avant déploiement, assurance qualité des mises à jour tarifaires.  
- **Dashboards Business** : création de tableaux de bord **Tableau** pour le suivi des souscriptions et résiliations, affaires nouvelles.   
- **Études statistiques & pricing** : modélisation des sinistres graves (>= 45.000€) (régression logistique, GLM) et optimisation des tarifs ; recalibration du modèle d’élasticité‑prix, quantification de l’impact de **±5%** de variation tarifaire sur le volume de ventes.

:::  
:::  
:::

::: {.timeline-event}
::: {.timeline-point .bg_4}
:::
::: {.timeline-content}
::: {.timeline-border .bg_4}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Data Analyst  
{{< fa building >}} **April Moto**  
{{< fa calendar-days >}} 04/2021 – 09/2021  
{{< fa location-dot >}} *14 Quai de Marmoutier, 37100 Tours, France*  

- **Optimisation du scraper** : refonte du script Python, augmentation du taux de succès de collecte de **70% → 92%** en 3 mois.  
- **Tableaux de bord Qlik Sense** : conception et déploiement de dashboards pour la veille concurrentielle tarifaire.
- **Modèle prédictif de résiliation** : implémentation d’un modèle de machine learning (**XGBoost**) atteignant **85%** de précision, intégré dans le CRM pour priorisation de la relance.  
- **Calcul de la Customer Lifetime Value** : élaboration d’une formule CLV tenant compte du taux de churn, valeur moyenne et coût d’acquisition.
- **KPI et reporting** : amélioration continue des dashboards **Qlik Sense** pour le suivi des indicateurs clés (acquisition, churn, évolution tarifaire).

:::  
:::  
:::

::: {.timeline-event}
::: {.timeline-point .bg_5}
:::
::: {.timeline-content}
::: {.timeline-border .bg_5}
:::
::: {.timeline-description}

## {{< fa graduation-cap >}} Master Data Science / Business Economics  
{{< fa calendar-days >}} 2019 – 2021  
{{< fa location-dot >}} *Faculté de Droit, économie et sciences sociales, 50 Avenue Jean Portalis, 37200 Tours, France*  

- **Majeure Data Science** : apprentissage approfondi en statistiques, machine learning, séries temporelles et bases de données.  
- **Projet clé** : mise en place d'un modèle de machine learning pour prédire le prix de vente de véhicules d'occasion en France. 
- **Mémoire stage de fin d'étude** : optimisation d'un scraper tarifaire en assurance pour deux-roues ; Mise en place d'un modèle prédictif de résiliation.
- **Outils & langages** : maîtrise de Python (Numpy, Pandas, scikit‑learn), R, SQL, Git, Jupyter, présentation de résultats avec PowerPoint, Beamer et outils BI.

::: {style="text-align:center;"}
[Mémoire fin d'étude {{< fa arrow-up-right-from-square >}}](/assets/memoire.pdf){.btn .btn-outline-primary .btn .center role="button"}
:::

::: {style="text-align:center;"}
[Github projet fin d'étude {{< fa arrow-up-right-from-square >}}](https://github.com/Francois-b-24/Second-hand-car-prices){.btn .btn-outline-primary .btn .center role="button"}
:::

:::  
:::  
:::

::: {.timeline-event}
::: {.timeline-point .bg_6}
:::
::: {.timeline-content}
::: {.timeline-border .bg_6}
:::
::: {.timeline-description}

## {{< fa graduation-cap >}} Licence d’Économie  
{{< fa calendar-days >}} 2016 – 2019  
{{< fa location-dot >}} *Faculté de Droit, économie et sciences sociales, 50 Avenue Jean Portalis, 37200 Tours, France*  

- **Fondamentaux économiques**: microéconomie, macroéconomie, économétrie et statistiques appliquées.  
- **Compétences analytiques**: manipulation de données, rédaction de rapports et communication des résultats en milieu académique et professionnel.

:::
:::
:::

:::  