---
title: "Compétences"
title-block-banner: true
toc: true
toc-title: 📋 Compétences
lang: fr
smooth-scroll: true
comments: false
author: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
```

::: {style="text-align:center;"}
*Sur cette page, vous trouverez une présentation de mes compétences.*
:::

### Théoriques

------------------------------------------------------------------------

::: {.callout-note icon="false" collapse="true"}
## Économie

-   **Micro-économie** : Théorie du consommateur & du producteur, équilibre de marché en concurrence pure et parfaite.
-   **Théorie des jeux** : Equilibre de nash (Modélisation mathématiques des interactions stratégiques entre les agents économiques).
-   **Économie industrielle** : Equilibre de Nash en situation non concurrentielle (Duopole, Monopole, Oligopole )
:::

::: {.callout-note icon="false" collapse="true"}
## Statistiques

-   **Analyse de données exploratoire**
-   **Économétrie** : Régression linéaire simple ou multiple, modèles à variable à expliquer dichotomiques, séries-temporelles, etc.
-   **Micro-économétrie** : Modèles à effets fixe ou aléatoires, etc.
-   **Machine Learning** : Regression, classification supervisée & non supervisée
-   **Deep Learning** : Réseaux de neurones
-   **Séries temporelles**
:::

### Outils techniques

------------------------------------------------------------------------

::: {.callout-tip icon="false" collapse="true"}
## {{< fa brands python >}} PYTHON

-   **Web Scraping (récupération automatique de données)** avec `beautifulsoup` et `selenium`.
-   **Nettoyage et traitement des données** avec `polars`, `pandas`, `numpy`.
-   **Visualisation des données** avec `plotly` et `seaborn`.
-   **Machine learning** : `Scikit learn`, `PyTorch`.
-   **Création d'application web** : `Streamlit`, `Flask` (en apprentissage).
-   **Développement de code de qualité industrielle** : `mypy` pour le typage statique, `ruff` pour le linting et le formatage du code, `pytest` pour les tests.
:::

::: {.callout-tip icon="false" collapse="true"}
## {{< fa brands r-project >}} R

-   **Nettoyage et traitement des données** avec **tidyverse** : `{dplyr}`, `{purrr}`, `{stringr}`, etc.
-   **Visualisation des données** avec `{ggplot2}` et `{plotly}`.
-   **Création d'application web et tableaux de bord** avec `{shiny}`
-   **Création de site web** avec `Quarto`
-   **Machine Learning** avec `{tidymodels}`.
-   **Analyse de données exploratoire et analyse factorielle** : ACP -- AFC -- ACM -- AFDM.
-   **Econométrie et de micro-économétrie** : `{micEcon}`, `{sfa}`, etc.
:::

::: {.callout-tip icon="false" collapse="true"}
## {{< fa database >}} SQL

-   Notion sur les bases de données relationnelles
-   Manipulation des données (`SELECT`, `WHERE`, `ORDER BY`, `LIMIT`, etc.)
-   Fonction et opérateurs (`COUNT`, `SUM`,`AVG`, etc.)
-   Jointures
-   Indexation et performance (Création `d'index` pour améliorer les performances de requêtes)
:::

::: {.callout-tip icon="false" collapse="true"}
## QlikSense

-   **Création de tableaux de bord interactifs**
-   **Gestion des scripts**
:::

::: {.callout-tip icon="false" collapse="true"}
## {{< fa file-excel >}} Excel

-   **Traitement de données** 
-   **Tableaux croisés dynamiques**
-   **Requêtage** par le biais de `PowerQuery`
-   **Automatisation de tâches** par le biais de `VBA`
:::

::: {.callout-tip icon="false" collapse="true"}
## {{< fa code-compare >}} Git

-   **Gestion de projet**
-   **Versionning**
:::

### Soft skills & centre d'intérêts

------------------------------------------------------------------------

::: {.callout-warning icon="false" collapse="true"}
## Communication

-   Aptitude à partager des resultats techniques à des publics non avisés.
:::

::: {.callout-warning icon="false" collapse="true"}
## Force de proposition

-   Aucune hésitation à proposer de nouvelles solutions.
:::

::: {.callout-warning icon="false" collapse="true"}
## Gestion du temps & rigourosité

-   Importance de la gestion optimale du temps.
-   Être rigoureux est primordiale afin d'assurer un niveau de résultat de haute qualité.
:::

::: {.callout-warning icon="false" collapse="true"}
## Curiosité

-   Toujours en veille sur les nouvelles pratiques et différentes évolutions du secteur.
:::

::: {.callout-warning icon="false" collapse="true"}
## Pragmatisme et adaptabilité

-   Facilité à m'adapter à des environnements hétérogènes.
:::

::: {.callout-warning icon="false" collapse="true"}
## Centre d'intérêts

-   **Intelligence Artificielle, Machine Learning**
-   **Technologie & Innovation**
-   **Économie & politique**
-   **Horlogerie**
-   **Sports mécaniques (F1, Moto GP, WRC, WEC)**
:::
